// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monetrixa.ChallengeApp.Infrastructure.Persistence;

#nullable disable

namespace Monetrixa.ChallengeApp.Infrastructure.Migrations
{
    [DbContext(typeof(ChallengeDbContext))]
    partial class ChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AccessCode")
                        .IsUnique();

                    b.ToTable("Challenge", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<string>("Quote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId", "DayNumber")
                        .IsUnique();

                    b.ToTable("ChallengeDay", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PublishedContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublishedContentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.DailyValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("PublishedContentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeDayId");

                    b.HasIndex("PublishedContentId");

                    b.HasIndex("UserId", "ChallengeDayId")
                        .IsUnique();

                    b.ToTable("DailyValidation", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.GeneratedIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("IdeaGenerationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdeaGenerationId");

                    b.ToTable("GeneratedIdeas");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.IdeaGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("PromptUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeDayId");

                    b.HasIndex("UserId");

                    b.ToTable("IdeaGenerations");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.PublishedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeDayId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeDayId");

                    b.HasIndex("UserId");

                    b.ToTable("PublishedContent", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("Resource", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.UserChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique();

                    b.ToTable("UserChallenge", (string)null);
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Days")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Comment", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.PublishedContent", "PublishedContent")
                        .WithMany("Comments")
                        .HasForeignKey("PublishedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PublishedContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.DailyValidation", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", "ChallengeDay")
                        .WithMany("DailyValidations")
                        .HasForeignKey("ChallengeDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.PublishedContent", "PublishedContent")
                        .WithMany("DailyValidations")
                        .HasForeignKey("PublishedContentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("DailyValidations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeDay");

                    b.Navigation("PublishedContent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.GeneratedIdea", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.IdeaGeneration", "IdeaGeneration")
                        .WithMany("GeneratedIdeas")
                        .HasForeignKey("IdeaGenerationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdeaGeneration");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.IdeaGeneration", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", "ChallengeDay")
                        .WithMany("IdeaGenerations")
                        .HasForeignKey("ChallengeDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("IdeaGenerations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengeDay");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.PublishedContent", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", "ChallengeDay")
                        .WithMany("PublishedContents")
                        .HasForeignKey("ChallengeDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("PublishedContents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChallengeDay");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Resource", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.Challenge", "Challenge")
                        .WithMany("Resources")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.UserChallenge", b =>
                {
                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Monetrixa.ChallengeApp.Domain.Entities.User", "User")
                        .WithMany("UserChallenges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Resources");

                    b.Navigation("UserChallenges");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.ChallengeDay", b =>
                {
                    b.Navigation("DailyValidations");

                    b.Navigation("IdeaGenerations");

                    b.Navigation("PublishedContents");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.IdeaGeneration", b =>
                {
                    b.Navigation("GeneratedIdeas");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.PublishedContent", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DailyValidations");
                });

            modelBuilder.Entity("Monetrixa.ChallengeApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("DailyValidations");

                    b.Navigation("IdeaGenerations");

                    b.Navigation("Notifications");

                    b.Navigation("PublishedContents");

                    b.Navigation("UserChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
